### ISSUE TITLE
"start_wt" is missing in the config

### ISSUE THREAD

**Issue by yangzhao1230** [haewonc/LatProtRL#1]
```
Traceback (most recent call last):
  File "optimize.py", line 52, in <module>
    cfg = create_opt(args)
  File "/home/v-zhaoyang2/project/LatProtRL/config.py", line 62, in create_opt
    opt.start_wt = args.start_wt
AttributeError: 'Namespace' object has no attribute 'start_wt'

```
It seems like that "start_wt" is not used in the optimize.py? Should I remove this argument directly?

**Comment by haewonc** [comment]
Yes, this is not used in the final version and should be removed. I will commit this right now. Thanks!
